ARG BASE_IMAGE_VERSION=55c5c6f-cuda-dev
ARG BASE_IMAGE=harbor.baai.ac.cn/flagos-dev/flagcx
FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}
# 
ARG VENDOR=USE_NVIDIA
# workdir
WORKDIR /workspace
COPY . /workspace/FlagCX
WORKDIR /workspace/FlagCX

# build
RUN make ${VENDOR}=1
