name: Docker Image Build Orchestrator

run-name: >-
  ${{ github.event_name == 'schedule' && github.event.schedule == '0 2 * * 0' && 'weekly' ||
      github.event_name == 'schedule' && 'daily' ||
      'ci' }}

on:
  schedule:
    - cron: '0 2 * * 1-6'
    - cron: '0 2 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: buildcx-nvidia-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'flagcx-nvidia'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagos-dev/flagcx
              BASE_IMAGE_VERSION=55c5c6f-cuda-dev
              VENDOR=USE_NVIDIA
          
          # use h20 instance just for build image.
          - job_name: buildcx-metax-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'flagcx-metax'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagos-base/flagos-base-metax-maca3.8.1.3
              BASE_IMAGE_VERSION=2.1.2
              VENDOR=USE_METAX

          # use h20 instance just for build image.
          - job_name: buildcx-ascend-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'flagcx-ascend'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagos-base/flagos-base-ascend-cann8.5.0
              BASE_IMAGE_VERSION=2.1.2
              VENDOR=USE_ASCEND

          # use h20 instance just for build image.
          - job_name: buildcx-tsingmicro-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'flagcx-tsingmicro'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagos-base/flagos-base-tsingmicro-tsm260610
              BASE_IMAGE_VERSION=2.1.2
              VENDOR=USE_TSM
    
    uses: flagos-ai/build-infra/.github/workflows/imagebuild.yml@main
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagcx'
      no-cache: ${{ matrix.no-cache }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
