name: Hygon DCU Unit Tests

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: hygon-unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hygon_unit_tests:
    name: Hygon DCU unit tests
    uses: ./.github/workflows/unit_tests_common.yml
    with:
      platform: hygon
