name: T-Head PPU Unit Tests

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ppu-unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ppu_unit_tests:
    name: T-Head PPU unit tests
    uses: ./.github/workflows/unit_tests_common.yml
    with:
      platform: ppu
